config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
	resources :posts do
		resources :comments
	end
	root 'posts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  validates :user_id, presence: true
  validates_length_of :comment, :minimum => 3, :maximum => 300

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  has_many :comments, dependent: :destroy   #says if the User is deleted, the post will be deleted aswell
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	

	

def create  
  @comment = @post.comments.build(comment_params)
  @comment.user_id = current_user.id

  if @comment.save
    respond_to do |format|
    	format.html { redirect_to root_path }
    	format.js
    end
  else
    flash[:alert] = "Check the comment form, something went horribly wrong."
    render root_path
  end
end

def destroy
  @comment = @post.comments.find(params[:id])
  
  if @comment.user_id == current_user.id
    @comment.delete
    respond_to do |format|
    format.html { redirect_to root_path }
    format.js
    end
  end
end

private

def comment_params  
  params.require(:comment).permit(:content)
end

def set_post  
  @post = Post.find(params[:post_id])
end  
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:create, :edit, :update, :destroy, :show]
	before_action :owned_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
        
        if @post.save
           flash[:success] = "Your post has been created!"
		   redirect_to posts_path
	    else 
	       flash.now[:alert] = "Your post has not been successfully created"
	       render :new
	    end
	end


	def show
		
	end

	def edit
		
	end

	def update
		
		if @post.update(post_params)
			flash[:success] = "Your Post has been updated!"
		    redirect_to posts_path
		else
			flash.now[:alert] = "Update failed!"
			render :edit
		end
	end

	def destroy
		
		if @post.destroy
            flash[:success] ="Your Post has been successfully terminated"
		    redirect_to posts_path
		else
			flash.now[:alert] = "Could not destroy that, sorry"
			render :edit
		end
	end


	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user 
		flash[:alert] = "That post doesn't belong to you!"
		redirect_to root_path
	    end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)  
       { success: 'alert-success',
       error: 'alert-danger',
       alert: 'alert-warning',
       notice: 'alert-info'
       }[flash_type.to_sym] || flash_type.to_s
    end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
    <%= comment.user.user_name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instanice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   

  <div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  </div>
   

  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>

  <% end %>
</div>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Instanice", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
         <li>
            <%= link_to "New Post", new_post_path %>
         </li>
         <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
         </li>
      <% else %>
         <li>
          <%= link_to "Register", new_user_registration_path %>
         </li>
         <li>
          <%= link_to "LogIn", new_user_session_path %>
         </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
      <div class="time-ago">
         <%= time_ago_in_words post.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'navbar' %>
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'navbar' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'navbar' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'navbar' %>

<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
   <div class="text-center edit-links">
      <%= link_to "Edit", edit_post_path(@post) %>
      |
      <%= link_to "Cancel", posts_path %>
   </div>
   <% else %>
   <div class="text-center edit-links">
      <%= link_to "Go back", posts_path %>
   </div>
   <% end %>